import os
import sys
import argparse
import logging
import time
from pathlib import Path
from typing import List, Tuple, Optional, Dict

import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from torch.optim import AdamW
from torch.optim.lr_scheduler import ExponentialLR
from torch.amp import GradScaler
from torch.amp import autocast


import albumentations as A
from albumentations.pytorch import ToTensorV2


# =============================================================================
# ADD DEPTH ANYTHING V2 TO PATH
# =============================================================================

import sys
sys.path.append("D:/ihub-data/ToM_Depth_Estimation/Depth-Anything-V2")

# -----------------------------------------------------------------------------
# Depth Anything V2
# -----------------------------------------------------------------------------
try:
    from depth_anything_v2.dpt import DepthAnythingV2
    print("Depth Aything v2 found")
except ImportError:
    print("[Error] Depth Aything v2 not found")
    sys.exit(1)

# logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-8s %(message)s",
    datefmt="%H:%M:%S"
)
log = logging.getLogger(__name__)

# Constants

TARGET_H, TARGET_W = 240, 320               # Orin Nano inference resolution
IMG_MEAN = (0.485, 0.456, 0.406)            # ImageNet / DA v2 normalisation
IMG_STD = (0.229, 0.224, 0.225)

# DA v2 Small model config
DA_V2_SMALL_CFG = {
    "encoder" : "vits",
    "features" : 64,
    "out_channels" : [48, 96, 192, 384]
}

class SILogLoss(nn.Module):
    """
    Scale-Invariant Logarithimic Loss from Eigen et al. (NeurIPS 2014).
    Standard loss for monocular depth fine-tuning.

    Robust to the unknown gloabl scale factor in monocular predictions -
    critical hare because pseudo-labels are relative depth maps.
    """
    def __init__(self, lambda_var: float =0.85, eps: float = 1e-6, valid_threshold: float = 1e-3, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.lambda_var = lambda_var
        self.eps = eps
        self.valid_threshold = valid_threshold

    def forward(
            self,
            pred: torch.Tensor,
            target: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            pred : Predicted depth [B,1,H,W] or [B,H,W], float32.
            target: Pseudo-label depth [B, 1, H, W] or [B, H, W], float32.
        
        Returns:
            Scalar loss tensor.
        """
        # Flatten to [B, H*W]
        if pred.dim() == 4:
            pred = pred.squeeze(1)
        if target.dim() == 4:
            target = target.squeeze(1)

        pred = pred.reshape(pred.shape[0], -1)
        target = target.reshape(target.shape[0], -1)

        # Valid mask: exclude zero/missing pseudo-label pixels
        valid = target > self.valid_threshold

        # Clamp prediction to positive -log requires > 0
        pred_c = pred.clamp(min=self.eps)
        target_c = target.clamp(min=self.eps)

        # Log difference: d_i = log(pred) - log(target)
        d = torch.log(pred_c) - torch.log(target_c)
        d = d * valid.float()   # zero out invalid pixels

        n = valid.float().sum(dim=1).clamp(min=1.0)  # [B] - valid pixel count

        # SILog formula
        d_sq_mean = (d**2).sum(dim=1)/n
        d_mean_sq = (d.sum(dim=1) / n) ** 2
        loss_per_b = torch.sqrt((d_sq_mean - self.lambda_var * d_mean_sq).clamp(min=0))

        return loss_per_b.mean()
    

# Dataset

class PseudoLabelDepthDataset(Dataset):
    """
    Loads (RGB image, pseudo-label depth .npy) pair for fine-tuning.
    Expects each data_dir to contain:
        images/ *.jpg or *.png
        depths/ *.npy - same filename stem as image

    Generated by generate_pseudo_labels.py

    Args:
        data_dirs : List of directories, sach with image/ and depths/.
        transform : albumentations pipeline applied to image only.
        depth_transform : Optional depth resizing/normolisation. 
    """

    IMG_EXTS = ["*.jpg", "*.jpeg", "*.png"]

    def __init__(self, data_dirs: List[str], transform: A.Compose,):
        super().__init__()
        self.transform = transform
        self.samples: List[Tuple[Path, Path]] = []
        self._build(data_dirs)

    def _build(self, data_dir: List[str]) -> None:
        for d in data_dir:
            img_dir = Path(d) / "images"
            dep_dir = Path(d) / "depths"

            if not img_dir.exists():
                raise FileNotFoundError(
                    f"images/ dir not found in {d}\n"
                    f"Expected: {img_dir}"
                )
            if not dep_dir.exists():
                raise FileNotFoundError(
                    f"depths/ dir not found in {d}\n",
                    f"Expected: {dep_dir}\n"
                )
            found = 0
            for ext in self.IMG_EXTS:
                for img_path in sorted(img_dir.glob(ext)):
                    dep_path = dep_dir / (img_path.stem + ".npy")
                    if dep_path.exists():
                        self.samples.append((img_path, dep_path))
                        found += 1
                    else:
                        log.warning(f"No .npy for {img_path.name} - skipping")
            log.info(f" {Path(d).name}: {found} samples")
        
        log.info(f"[Dataset] Total: {len(self.samples)} samples")

    def __len__(self):
        return len(self.samples)
    
    def __getitem__(self, index: int) -> Dict[str, torch.Tensor]:
        img_path, dep_path = self.samples[index]
        # load image
        image = np.array(Image.open(img_path).convert("RGB"), dtype=np.uint8)
        # load pseudo-label path
        depth = np.load(dep_path).astype(np.float32)  # [H, W] relative depth

        # Resize depth to training resolution if needed
        if depth.shape != (TARGET_H, TARGET_W):
            depth = np.array(
                Image.fromarray(depth).resize(
                    (TARGET_H, TARGET_W), Image.BILINEAR
                )
            )
        
        # Apply image transforms
        result = self.transform(image=image)
        img_t = result["image"] # [3, H, W] float32

        # Depth - tensor [1, H, W]
        dep_t = torch.from_numpy(depth).unsqueeze(0)  # [1, H, W] float32

        return {
            "image" : img_t,
            "depth" : dep_t,
            "stem"  : img_path.stem,
        }
    


# Transfoms

def _train_tf() -> A.Compose:
    return A.Compose([
        A.Resize(TARGET_H,TARGET_W),
        A.HorizontalFlip(p=0.5),
        A.RandomBrightnessContrast(0.2,0.2, p=0.6),
        A.HueSaturationValue(10, 20, 10, p=0.4),
        A.GaussianBlur(blur_limit=(3,5), p=0.2),
        A.Normalize(mean=IMG_MEAN, std=IMG_STD),
        ToTensorV2(),
    ])

def _val_tf() -> A.Compose:
    return A.Compose([
        A.Resize(TARGET_H, TARGET_W),
        A.Normalize(mean=IMG_MEAN, std=IMG_STD),
        ToTensorV2(),
    ])

# Model

def build_model(pretrained_path: str, device: torch.device) -> nn.Module:
    """
    Load Depth Anything v2-small with pretrained weights.

    Args:
        pretrained_path  : Path to .pth checkpoint.
        device           : Target device.
    Returns:
        Model in train mode on device
    """

    model = DepthAnythingV2(**DA_V2_SMALL_CFG)

    if not Path(pretrained_path).exists():
        raise FileNotFoundError(
            f"Pretrained weights not found: {pretrained_path}\n"
            "Download from: https://github.com/DepthAnything/Depth-Anything-v2"
        )
    
    state = torch.load(pretrained_path, map_location="cpu")

    # Handle various checkpoint fromats

    if "model" in state:
        state = state["model"]
    elif "state_dict" in state:
        state = state["state_dict"]

    missing, unexpected = model.load_state_dict(state, strict=False)
    if missing:
        log.warning(f"Missing keys : {len(missing)} - {missing[:3]} ...")
    if unexpected:
        log.warning(f"Unexpected keys : {len(unexpected)} - {unexpected[:3]} ...")

    log.info(f"[Model] Loaded DA v2-Small from {pretrained_path}")
    return model.to(device).train()

# Metrics

@torch.no_grad()
def compute_metrics(pred: torch.Tensor, target: torch.Tensor, valid_threshold: float = 1e-3,) -> Dict[str, float]:
    """
    Compute depth evalution metrics on a batch.

    Return dict with: abs_rel, rmse, silog, deltas_1
    """

    if pred.dim() == 4: pred = pred.squeeze(1)
    if target.dim() == 4: target = target.squeeze(1)

    valid = target > valid_threshold
    pred_v = pred[valid].clamp(min=1e-6)
    tgt_v = target[valid].clamp(min=1e-6)

    if tgt_v.numel() == 0:
        return {"abs_rel": 0.0, "rsme": 0., "silog": 0.,"delta_1": 0.}
    
    # Scale-align to pred to target for metric computation
    # (monocular prediction are relative - allign scale via median ratio)
    scale = torch.median(tgt_v)/torch.median(pred_v)
    pred_v = pred_v* scale

    abs_rel = ((pred_v - tgt_v).abs() / tgt_v).mean().item()
    rmse = ((pred_v - tgt_v)**2).mean().sqrt().item()

    d = torch.log(pred_v) - torch.log(tgt_v)
    n = d.numel()
    silog = torch.sqrt(
        (d ** 2).mean() - 0.85 * (d.mean()**2)
    ).item()
    thres = torch.max(pred_v/ tgt_v, tgt_v/pred_v)
    delta_1 = (thres < 1.25).float().mean().item()

    return{
        "abs_rel" : abs_rel,
        "rmse"    : rmse,
        "silog"   : silog,
        "delta_1" : delta_1  
    }

# Training Loop

def train(args: argparse.Namespace) -> None:
    # -----------Device------------------------
    device = torch.device(
        "cuda" if torch.cuda.is_available() else "cpu"
    )
    log.info(f"[Train] Device: {device}")
    if device.type == "cpu":
        log.warning("No GPU found - training will be very slow")
    
    # --------------Output directory-----------
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    log.info(f"[Train] checkpoints - {out_dir}")


    # ------------Datase & DataLoaders-------------------
    log.info("[Train] Building dataset ..........")
    full_ds = PseudoLabelDepthDataset(args.data_dirs, transform=_train_tf())

    val_size = max(1, int(len(full_ds) * args.val_split))
    trn_size = len(full_ds) - val_size
    generator = torch.Generator().manual_seed(42)
    train_ds, _ = random_split(full_ds, [trn_size, val_size], generator=generator)

    # Val set uses val transforms - rebuild with val_tf
    val_full_ds = PseudoLabelDepthDataset(args.data_dirs, transform=_val_tf())
    _, val_ds = random_split(val_full_ds,[trn_size,val_size], generator=generator)

    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True,
        drop_last=True
    )

    val_loader = DataLoader(
        val_ds, 
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True,
        drop_last=False
    )

    log.info(f"[Train] Train: {trn_size} Val: {val_size}"
             f"Batch: {args.batch_size}"
             f"steps/epoch: {len(train_loader)}")
    
    # ------------Model------------------------------------------
    model = build_model(args.pretrained, device)

    # ------------Loss-------------------------------------------
    criterion = SILogLoss(lambda_var=0.85)

    # ----------Optimizer & Scheduler ---------------------------
    # lr=1e-7 is intentionally very low 
    # Higher LR destroys the model existing generalization
    optimizer = AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4, betas=(0.9, 0.999))
    scheduler = ExponentialLR(optimizer, gamma=0.95)

    # -------------Mixed Precision Scaler----------------------
    use_amp = (device.type == "cuda")
    scaler = GradScaler("cuda", enabled=use_amp)

    # -----------------Resume from checkpoints-----------------
    start_epoch = 0
    best_silog = float("inf")

    resume_path = out_dir / "last_checkpoint.pth"
    if args.resume and resume_path.exists():
        ckpt = torch.load(resume_path, map_location=device)
        model.load_state_dict(ckpt["model"])
        scheduler.load_state_dict(ckpt["scheduler"])
        start_epoch = ckpt["epoch"] + 1
        best_silog = ckpt.get("best_silog", float("inf"))
        log.info(f"[Resume] Epoch {start_epoch}, best SILog={best_silog:.4f}")
        # ----------------- Training Epochs ---------------------
        log.info(f"\n{'-'*60}")
        log.info(f" Starting fine-tuning: {args.epochs} epochs")
        log.info(f" LR={args.lr:.2e} decay gamma= 0.95 loss = SILog(gamma=0.85)")
        log.info(f"\n{'-'*60}")

    for epoch in range(start_epoch, args.epochs):
        t0 = time.time()
    # -------------------Train Phase--------------------------
        model.train()
        train_loss = 0.0
        train_steps = 0
        for step, batch in enumerate(train_loader):
            images = batch["image"].to(device, non_blocking=True) # [B,3, H, W]
            depths = batch["depth"].to(device, non_blocking=True) # [B, 1, H, W]

            optimizer.zero_grad(set_to_none=True)
            with autocast(device_type="cuda", enabled=use_amp):
                # DA v2 forward pass - [B, H, W] relative depth
                pred = model(images)

                # Ensure [B, 1, H, W] for loss
                if pred.dim() == 3:
                    pred = pred.unsqueeze(1)
                # Resize prediction to match pseudo-label resolution if needed
                if pred.shape[-2:] != depths.shape[-2:]:
                    pred = F.interpolate(
                        pred, size=depths.shape[-2:],
                        mode="bilinear", align_corner=False
                    )
                loss = criterion(pred, depths)

            scaler.scale(loss).backward()
            # Gradient clipping - prevants instability at very low LR
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            scaler.step(optimizer)
            scaler.update()
            train_loss += loss.item()
            train_steps += 1

            # --------Step-level logging every 10 steps
            if (step + 1) % 100 == 0:
                avg = train_loss / train_steps
                lr = optimizer.param_groups[0]["lr"]
                log.info(
                    f" Epoch { epoch+1:>3}/{args.epochs} "
                    f"Step { step+1:>4}/{len(train_loader)} "
                    f"Loss={avg:.5} LR={lr:.2e}"
                )
        avg_train_loss = train_loss / max(train_steps, 1)
        scheduler.step()

        # ----------------------Validation Phase----------------
        model.eval()
        val_loss = 0.0
        val_steps = 0
        val_matrices = {"abs_rel": 0.0, "rmse":0.0, "silog":0., "delta_1": 0.0}

        with torch.no_grad():
            for batch in val_loader:
                images = batch["image"].to(device, non_blocking=True)
                depths = batch["depth"].to(device, non_blocking=True)

                with autocast(device_type="cuda", enabled=use_amp):
                    pred = model(images)
                    if pred.dim() == 3:
                        pred = pred.unsqueeze(1)
                    if pred.shape[-2:] != depths.shape[-2:]:
                        pred = F.interpolate(
                            pred,size=depths.shape[-2:],
                            mode='bilinear', align_corners=False
                        )
                    loss = criterion(pred, depths)
                val_loss += loss.item()
                val_steps += 1

                m = compute_metrics(pred, depths)
                for k, v in m.items():
                    val_matrices[k] += v
        avg_val_loss = val_loss / max(val_steps, 1)
        for k in val_matrices:
            val_matrices[k] /= max(val_steps, 1)
        elapsed = time.time() - t0
        lr_now = optimizer.param_groups[0]['lr']

        #------------Epoch Summary----------------------------
        log.info(
            f"\nEpoch {epoch+1:>3}/{args.epochs} ({elapsed:.0f}s)"
            f"LR={lr_now:.2e}\n"
            f" Train Loss : {avg_train_loss:.5f}\n"
            f" Val Loss : {avg_val_loss:.5f}\n"
            f" abs_rel : {val_matrices['abs_rel']:.4f}\n"
            f" rmse : {val_matrices['rmse']:.4f}\n"
            f" silog : {val_matrices['silog']:.4f}\n"
            f" delta_1 : {val_matrices['delta_1']:.4f}\n"
            f" (target > 0.85)\n"
        )

        # ------------------------ Save last checkpoints (always) -------------------------
        torch.save({
            "epoch" : epoch,
            "model" : model.state_dict(),
            "optimizer" : optimizer.state_dict(),
            "scheduler" : scheduler.state_dict(),
            "best_silog" : best_silog,
            "val_loss" : avg_val_loss,
            "val_matrices" : val_matrices
        }, out_dir / "last_checkpoint.pth")

        # --------------------Save best model (lowest SILog)---------------------------
        if val_matrices["silog"] < best_silog:
            best_silog = val_matrices["silog"]
            torch.save(
                model.state_dict(), 
                out_dir / "best_model.pth"
                )
            log.info(f" Best model saved (SILog={best_silog:.5f})")
    log.info(f"\n{'-'*60}")
    log.info(f" Best SILog : {best_silog:.5f}")
    log.info(f" Best model : {out_dir / 'best_model.pth'}")
    log.info(f"{'-'*60}\n")

# Domain fine-tuning convenience wrapper

def domain_finetune(
        real_data_dir: str,
        pretrained_path: str,
        output_dir: str,
        epochs: int = 10,
        lr: float = 1e-8,
        batch_size: int = 4,
) -> None:
    """
    Domain fine-tune on real environment frames.

    Separate call after main fine-tuning completes
    Use lower LR (1e-8) after fewer epochs
    """
    args = argparse.Namespace(
        data_dirs = [real_data_dir],
        pretrained = pretrained_path,
        output_dir= output_dir,
        epochs= epochs,
        lr = lr,
        batch_size = batch_size,
        num_workers = 2,
        val_split = 0.15, # hold out 15% of small real-frame set
        resume = False
    )

    log.info("\n" + "="*60)
    log.info(" Domain fine-tuning on real environment frames")
    log.info("="*60)
    train(args)

# CLI

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Fine-tune Depth Anything v2-Small "
        "for glass-aware relative depth estimation"
    )
    p.add_argument(
        "--data_dirs", nargs="+", required=True,
        help="One or more directories, each with images/ and depth/ subdirs"
    )
    p.add_argument(
        "--pretrained", required=True,
        help="Path to DA v2-Small pretrained .pth weights"
    )
    p.add_argument(
        "--output-dir", default="checkpoints/finetuned",
        help="Directory to save checkpoints"
    )
    p.add_argument("--epochs", type=int, default=20)
    p.add_argument("--batch_size", type=int, default=8)
    p.add_argument("--lr", type=float, default=1e-7)
    p.add_argument("--num_workers", type=int, default=4)
    p.add_argument("--val_split", type=float, default=0.1)
    p.add_argument("--resume", action="store_true",
                   help="Resume from last_checkpoint.pth in output_dir")
    p.add_argument("--domain_finetune", action="store_true",
                   help="Run domain fine-tune"
                   "(uses lr=1e-8, epochs=10 on --data_dirs)")
    return p.parse_args()

# Entry point

if __name__ == "__main__":
    args = parse_args()
    if args.domain_finetune:
        # pass single real-frames dir
        assert len(args.data_dirs) == 1, "--domain_finetune expect on --data_dir entry (real_frames)"
        domain_finetune(
            real_data_dir= args.data_dirs[0],
            pretrained_path = args.pretrained,
            output_dir= args.output_dir,
            epochs=10,
            lr = 1e-8,
            batch_size=args.batch_size,
        )
    else:
        train(args)

        


