import os
import sys
import argparse
import logging
import time
from pathlib import Path
from typing import List, Tuple, Optional, Dict

import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from torch.optim import AdamW
from torch.optim.lr_scheduler import ExponentialLR
from torch.cuda.amp import GradScaler
import albumentations as A
from albumentations.pytorch import ToTensorV2


# =============================================================================
# ADD DEPTH ANYTHING V2 TO PATH
# =============================================================================

import sys
sys.path.append("D:/ihub-data/ToM_Depth_Estimation/Depth-Anything-V2")

# -----------------------------------------------------------------------------
# Depth Anything V2
# -----------------------------------------------------------------------------
try:
    from depth_anything_v2.dpt import DepthAnythingV2
    print("Depth Aything v2 found")
except ImportError:
    print("[Error] Depth Aything v2 not found")
    sys.exit(1)

# logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-8s %(message)s",
    datefmt="%H:%M:%S"
)
log = logging.getLogger(__name__)

# Constants

TARGET_H, TARGET_W = 240, 320               # Orin Nano inference resolution
IMG_MEAN = (0.485, 0.456, 0.406)            # ImageNet / DA v2 normalisation
IMG_STD = (0.229, 0.224, 0.225)

# DA v2 Small model config
DA_V2_SMALL_CFG = {
    "encoder" : "vits",
    "features" : 64,
    "out_channels" : [48, 96, 192, 384]
}

class SILogLoss(nn.Module):
    """
    Scale-Invariant Logarithimic Loss from Eigen et al. (NeurIPS 2014).
    Standard loss for monocular depth fine-tuning.

    Robust to the unknown gloabl scale factor in monocular predictions -
    critical hare because pseudo-labels are relative depth maps.
    """
    def __init__(self, lambda_var: float =0.85, eps: float = 1e-6, valid_threshold: float = 1e-3, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.lambda_var = lambda_var
        self.eps = eps
        self.valid_threshold = valid_threshold

    def forward(
            self,
            pred: torch.Tensor,
            target: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            pred : Predicted depth [B,1,H,W] or [B,H,W], float32.
            target: Pseudo-label depth [B, 1, H, W] or [B, H, W], float32.
        
        Returns:
            Scalar loss tensor.
        """
        # Flatten to [B, H*W]
        if pred.dim() == 4:
            pred = pred.squeeze(1)
        if target.dim() == 4:
            target = target.squeeze(1)

        pred = pred.reshape(pred.shape[0], -1)
        target = target.reshape(target.shape[0], -1)

        # Valid mask: exclude zero/missing pseudo-label pixels
        valid = target > self.valid_threshold

        # Clamp prediction to positive -log requires > 0
        pred_c = pred.clamp(min=self.eps)
        target_c = target.clamp(min=self.eps)

        # Log difference: d_i = log(pred) - log(target)
        d = torch.log(pred_c) - torch.log(target_c)
        d = d * valid.float()   # zero out invalid pixels

        n = valid.float().sum(dim=1).clamp(min=1.0)  # [B] - valid pixel count

        # SILog formula
        d_sq_mean = (d**2).sum(dim=1)/n
        d_mean_sq = (d.sum(dim=1) / n) ** 2
        loss_per_b = torch.sqrt((d_sq_mean - self.lambda_var * d_mean_sq).clamp(min=0))

        return loss_per_b.mean()
    

# Dataset

class PseudoLabelDepthDataset(Dataset):
    """
    Loads (RGB image, pseudo-label depth .npy) pair for fine-tuning.
    Expects each data_dir to contain:
        images/ *.jpg or *.png
        depths/ *.npy - same filename stem as image

    Generated by generate_pseudo_labels.py

    Args:
        data_dirs : List of directories, sach with image/ and depths/.
        transform : albumentations pipeline applied to image only.
        depth_transform : Optional depth resizing/normolisation. 
    """

    IMG_EXTS = ["*.jpg", "*.jpeg", "*.png"]

    def __init__(self, data_dirs: List[str], transform: A.Compose,):
        super().__init__()
        self.transform = transform
        self.samples: List[Tuple[Path, Path]] = []
        self._build(data_dirs)

    def _build(self, data_dir: List[str]) -> None:
        for d in data_dir:
            img_dir = Path(d) / "images"
            dep_dir = Path(d) / "depths"

            if not img_dir.exists():
                raise FileNotFoundError(
                    f"images/ dir not found in {d}\n"
                    f"Expected: {img_dir}"
                )
            if not dep_dir.exists():
                raise FileNotFoundError(
                    f"depths/ dir not found in {d}\n",
                    f"Expected: {dep_dir}\n"
                )
            found = 0
            for ext in self.IMG_EXTS:
                for img_path in sorted(img_dir.glob(ext)):
                    dep_path = dep_dir / (img_path.stem + ".npy")
                    if dep_path.exists():
                        self.samples.append((img_path, dep_path))
                        found += 1
                    else:
                        log.warning(f"No .npy for {img_path.name} - skipping")
            log.info(f" {Path(d).name}: {found} samples")
        
        log.info(f"[Dataset] Total: {len(self.samples)} samples")

    def __len__(self):
        return len(self.samples)
    
    def __getitem__(self, index: int) -> Dict[str, torch.Tensor]:
        img_path, dep_path = self.samples[index]
        # load image
        image = np.array(Image.open(img_path).convert("RGB"), dtype=np.uint8)
        # load pseudo-label path
        depth = np.load(dep_path).astype(np.float32)  # [H, W] relative depth

        # Resize depth to training resolution if needed
        if depth.shape != (TARGET_H, TARGET_W):
            depth = np.array(
                Image.fromarray(depth).resize(
                    (TARGET_H, TARGET_W), Image.BILINEAR
                )
            )
        
        # Apply image transforms
        result = self.transform(image=image)
        img_t = result["image"] # [3, H, W] float32

        # Depth - tensor [1, H, W]
        dep_t = torch.from_numpy(depth).unsqueeze(0)  # [1, H, W] float32

        return {
            "image" : img_t,
            "depth" : dep_t,
            "stem"  : img_path
        }


